### ISSUE TITLE
adding section for about the organisation.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-IN/Catalyst#11]

**Comment by vinayaksh42** [comment]
i will do it

**Comment by Amankumar29** [comment]
Do we need this @anubhavsingh16

**Comment by vinayaksh42** [comment]
is this section still required @anubhavsingh16 ?
we already have a section about the aim , what we are, what we do ?

**Comment by anubhavsingh16** [comment]
I think aim covers about us section so need to add a new section of about us

**Comment by Amankumar29** [comment]
no need or need?
@anubhavsingh16

**Comment by anubhavsingh16** [comment]
no need sorry
