### ISSUE TITLE
Deployment of the website

### ISSUE THREAD

**Issue by codetheorem** [Catalyst-IN/Catalyst#27]
**Description of the enhancement**
Deploy the website for testing and reviewing

**Comment by anubhavsingh16** [comment]
@codetheorem please take help from @aryamanpuri if you need in deployment.

**Comment by aryamanpuri** [comment]
I will deploy it on netlify soon
@anubhavsingh16 @codetheorem

**Comment by Amankumar29** [comment]
I think it's done now.
