### ISSUE TITLE
How Can I Support Catalyst

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/Catalyst#34]
**Description of the enhancement**
### Add How Can I Support Catalyst section.

- Become a contributor and solve a bug, implement a new feature or write a unit test.
- Sponsor FOSSASIA events and programs as a company partner.

take reference from http://fossasia.org
![support](https://user-images.githubusercontent.com/47811606/83300766-3b887400-a216-11ea-8879-2b46f5063e61.png)

**Comment by codetheorem** [comment]
I will do it.

**Comment by anubhavsingh16** [comment]
yess do it 👍
