### ISSUE TITLE
Add memories section

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/Catalyst#35]
**Description of the enhancement**
Add memories section on the main page and add images of meetings and group.

**Screenshots**
![mem](https://user-images.githubusercontent.com/47811606/83301135-ba7dac80-a216-11ea-879a-bbc94b52db69.png)

**Comment by BhuwanChandra** [comment]
@anubhavsingh16 I would like to work on this one!

**Comment by anubhavsingh16** [comment]
@BhuwanChandra Can you work on #52 first because issue number #52 is urgent. After #52 I can assign you this issue.

**Comment by BhuwanChandra** [comment]
@anubhavsingh16  yes, I can work on that.

**Comment by anubhavsingh16** [comment]
Ok thats great
