### ISSUE TITLE
Add content in `Who we are`

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/Catalyst#37]
**Description of the enhancement**
### Add this content in `Who we are`. 

- We are an organization of people from all over the world. We want to see progress and improvements of people's lives in Asia and everywhere. We are developers, designers, event organizers and contributors who want to learn and share ideas, create and make digital software tools and hardware, that benefit people around the world.

### and in `What we do`
- We bring amazing people together to create, develop, design and make things with Open Technologies - hardware and software - and share our work for the benefit of all.

**Comment by vinayaksh42** [comment]
assign this to me

**Comment by anubhavsingh16** [comment]
okk
