### ISSUE TITLE
Align buttons in the active projects section to centre

### ISSUE THREAD

**Issue by JanviMahajan14** [Catalyst-IN/Catalyst#54]
**Expected behaviour**
1. Align the "Know More" buttons to centre
2. Remove the underline in the links provided within the buttons

**Comment by vinayaksh42** [comment]
i dont think it will look good
current:
![chrome_FNpD0jx7kf](https://user-images.githubusercontent.com/54861487/83765007-4587f800-a698-11ea-9f5e-9f6b4da745c4.png)
after:
![chrome_NRgWIBlq5Y](https://user-images.githubusercontent.com/54861487/83765011-46b92500-a698-11ea-8654-97e53dab241c.png)

what is your opinion @anubhavsingh16 , the rest of the content is left aligned.

**Comment by anubhavsingh16** [comment]
Yes its nice

**Comment by JanviMahajan14** [comment]
@vinayaksh42  This looks good to me. You can raise a PR.
